### ISSUE TITLE
Urgent: Discrepancies between original r8s vs pyr8s Estimation of rates and times

### ISSUE THREAD

**Issue by kamalmdmostafa** [iTaxoTools/pyr8s#4]
I was looking for the original r8s source code everywhere, but I had no luck until I came across your awesome pyr8s. I appreciate it. However, I have some concerns. 

In the original `divtime` command, r8s input #NEXUS trees use the following parameters. 

`divtime method=LF|NPRS|PL algorithm=POWELL|TN|QNEWT;`

However, in pyr8s GUI, when I input a nexus tree with `divtime method=PL algorithm=TN` it gives an error message saying wrong method. 

Then I checked the trees in the [tests folder ](https://github.com/iTaxoTools/pyr8s/tree/main/tests). The example trees contain `divtime method=np algorithm=pl,` which contradicts the original r8s tree input format.

**Comment by StefanPatman** [comment]
Thank you for the kind words. Unfortunately, only method=NPRS and algorithm=Powell are implemented in the program.
There are currently no plans to implement any other options, but I would happily merge any code contributions.

I am attaching the original source code for the command-line tool that I used as reference during development in case it cannot be found anywhere else:
- [r8s1.81.tar.gz](https://github.com/iTaxoTools/pyr8s/files/13708431/r8s1.81.tar.gz)
- [README.txt](https://github.com/iTaxoTools/pyr8s/files/13708430/README.txt)

Please notice that the attached version does not include all original methods due to licensing issues with the code. Hopefully this can be of some use to you.

**Comment by kamalmdmostafa** [comment]
Thank you so much, Stefan, for your prompt feedback. I really appreciate it. The Fortran 2018 deleted feature: DO termination statement which is not END DO. I was having trouble installing it in Linux. I figured that out by installing fortran9 and gcc5 and modifying the `Makefile.linux` file, I will write instructions on what changes I made in the `Makefile.linux `file ASAP. But pyr8s is the most convenient for quick analysis.
